spring.application.name=teacher-service

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

# PostgreSQL Configuration (for future use)
# spring.datasource.url=jdbc:postgresql://localhost:5432/school_timetable
# spring.datasource.username=postgres
# spring.datasource.password=password
# spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.show-sql=false

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/school_timetable
spring.datasource.username=postgres
spring.datasource.password=92844
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging Configuration
logging.level.root=INFO
logging.level.com.school.timetable=DEBUG
logging.level.org.springframework.cloud=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n